### ISSUE TITLE
compilation of ast fails

### ISSUE THREAD

**Issue by josch** [WeiDUorg/elkhound#2]
Here a log:

    [...]
    g++ -c -o agrampar.tab.o agrampar.tab.cc -g -Wall -Wno-deprecated -D__UNIX__ -O2 -DNDEBUG -D__LINUX__ -I../smbase
    agrampar.tab.c: In function ‘int agrampar_yyparse()’:
    agrampar.tab.c:1273:30: error: too few arguments to function ‘int agrampar_yylex(YYSTYPE*, void*)’
    In file included from agrampar.y:8:0:
    agrampar.h:59:5: note: declared here
     int agrampar_yylex(union YYSTYPE *lvalp, void *parseParam);
         ^
    agrampar.y:116:39: error: ‘parseParam’ was not declared in this scope
                    { $$ = *((ASTSpecFile**)parseParam) = new ASTSpecFile($1); }
                                           ^
    In file included from agrampar.y:8:0:
    agrampar.h:33:23: error: ‘parseParam’ was not declared in this scope
     #define YYPARSE_PARAM parseParam
                           ^
    agrampar.h:56:40: note: in expansion of macro ‘YYPARSE_PARAM’
     #define yyerror(m) agrampar_yyerror(m, YYPARSE_PARAM)
                                            ^
    agrampar.tab.c:1838:7: note: in expansion of macro ‘yyerror’
    agrampar.h:33:23: error: ‘parseParam’ was not declared in this scope
     #define YYPARSE_PARAM parseParam
                           ^
    agrampar.h:56:40: note: in expansion of macro ‘YYPARSE_PARAM’
     #define yyerror(m) agrampar_yyerror(m, YYPARSE_PARAM)
                                            ^
    agrampar.tab.c:1982:3: note: in expansion of macro ‘yyerror’
    Makefile:41: recipe for target 'agrampar.tab.o' failed
    make: *** [agrampar.tab.o] Error 1

I'm running this on Debian Jessie with g++-4.9.

**Comment by nerdouille** [comment]
Hi, any fix/hack for building on jessie (other than recompiling bison 2.5) ? I'm also stuck with bison 3.0.2 :/

**Comment by FredrikLindgren** [comment]
Sorry, I haven't had time to work on Elkhound.

**Comment by mbrethen** [comment]
These patches work with bison 3.04:

--- ast/agrampar.y.orig	2015-11-24 12:09:47.000000000 -0600
+++ ast/agrampar.y	2015-11-24 12:11:05.000000000 -0600
@@ -23,7 +23,9 @@
 
 /* ================== bison declarations =================== */
 // don't use globals
-%pure_parser
+%pure-parser
+%parse-param {void* parseParam}
+%lex-param {void* parseParam}
 
 
 /* ===================== tokens ============================ */


--- ast/agrampar.h.orig	2015-11-25 17:56:23.000000000 -0600
+++ ast/agrampar.h	2015-11-25 18:00:35.000000000 -0600
@@ -13,7 +13,7 @@
 // name of extra parameter to yyparse (i.e. the context in
 // which the parser operates, instead of that being stored
 // in some collection of globals)
-#define YYPARSE_PARAM parseParam
+//#define YYPARSE_PARAM parseParam
 
 // type of thing extra param points at
 struct ASTParseParams {
@@ -30,8 +30,8 @@
 // caller interface to Bison-generated parser; starts parsing
 // (whatever stream lexer is reading) and returns 0 for success and
 // 1 for error; the extra parameter is available to actions to use
-#define YYPARSE_PARAM parseParam
-int agrampar_yyparse(void *YYPARSE_PARAM);
+//#define YYPARSE_PARAM parseParam
+int agrampar_yyparse(void *parseParam);
 
 // when this is set to true, bison parser emits info about
 // actions as it's taking them
@@ -52,13 +52,13 @@
 CtorArg *parseCtorArg(rostring str);
 
 // error routine
-void agrampar_yyerror(char const *msg, void *parseParam);
-#define yyerror(m) agrampar_yyerror(m, YYPARSE_PARAM)
+void agrampar_yyerror(void *parseParam, char const *msg);
+#define yyerror(parseParam, m) agrampar_yyerror(parseParam, m)
 
 // parser's view of the lexer
 int agrampar_yylex(union YYSTYPE *lvalp, void *parseParam);
 #define yylex agrampar_yylex
-#define YYLEX_PARAM parseParam
+//#define YYLEX_PARAM parseParam
 
 // classify token codes
 bool isAGramlexEmbed(int code);

**Comment by FredrikLindgren** [comment]
Thanks. But are you sure those are all the changes you made? You'd at least additionally need to make the same change to agrampar_yyerror in agrampar.cc

**Comment by mbrethen** [comment]
I missed that one! At the end I was getting 

:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[1]: *** [astgen] Error 1

I'm not sure what to do next?

**Comment by FredrikLindgren** [comment]
Honestly, I don't know. I'm not familiar with Clang or what it would be missing. Do you know if there is some way to have it print which symbol(s) it is missing?

Ast builds with GCC against Bison 3 (3.0.2 on my end) after the changes you made (and some additional cruft dealing with the creation of agrampar.codes.h). I've pushed the progress thus far to the bison3 branch. Elkhound itself fails to build on account of the same incompatibility (and similar cruft with grampar.codes.h), but making what, to me, seems like the corresponding changes fails to resolve it. Presumably you need to know what you are doing.

**Comment by mbrethen** [comment]
Fixed agrampar.cc as you pointed out and then applied this patch:
```
--- src/ast/Makefile.in.orig	2015-11-29 17:16:43.000000000 -0600
+++ src/ast/Makefile.in	2015-11-29 17:23:56.000000000 -0600
@@ -65,8 +65,7 @@
 	mv -f agrampar.tab.h tmp
 	sed -e 's/typedef union {/typedef union YYSTYPE {/' < tmp > agrampar.tab.h
 	rm tmp
-	head -n 73 agrampar.tab.h > agrampar.codes.h
-#	grep '# *define' agrampar.tab.h > agrampar.codes.h
+	grep -A 2 -B 5 TOK_ agrampar.tab.h > agrampar.codes.h
 
 agrampar.tab.o: ast.hand.h ast.ast.h agrampar.h
 
```
I now get astgen to build. On to elkhound...
```
--- src/elkhound/grampar.cc.orig	2015-11-29 18:18:37.000000000 -0600
+++ src/elkhound/grampar.cc	2015-11-29 18:19:37.000000000 -0600
@@ -911,7 +911,7 @@
 }
 
 
-void grampar_yyerror(char const *message, void *parseParam)
+void grampar_yyerror(void *parseParam, char const *message)
 {
   ParseParams *par = (ParseParams*)parseParam;
   std::cout << par->lexer.curLocStr() << ": " << message << std::endl;

```
```
--- src/elkhound/grampar.h.orig	2015-11-29 18:12:01.000000000 -0600
+++ src/elkhound/grampar.h	2015-11-29 18:13:31.000000000 -0600
@@ -23,7 +23,7 @@
 // name of extra parameter to yyparse (i.e. the context in
 // which the parser operates, instead of that being stored
 // in some collection of globals)
-#define YYPARSE_PARAM parseParam
+//#define YYPARSE_PARAM parseParam
 
 // type of thing extra param points at
 struct ParseParams {
@@ -59,7 +59,7 @@
 int grampar_yylex(union YYSTYPE *lvalp, void *parseParam);
 
 // error printer
-void grampar_yyerror(char const *message, void *parseParam);
+void grampar_yyerror(void *parseParam, char const *message);
 
 
 // ---------------- grampar's parsing structures ---------------
```
```
--- src/elkhound/grampar.y.orig	2015-11-29 17:42:55.000000000 -0600
+++ src/elkhound/grampar.y	2015-11-29 17:52:24.000000000 -0600
@@ -19,14 +19,14 @@
 #endif
 
 // name of extra parameter to yylex
-#define YYLEX_PARAM parseParam
+//#define YYLEX_PARAM parseParam
 
 // make it call my yylex
 #define yylex(lv, param) grampar_yylex(lv, param)
 
 // Bison calls yyerror(msg) on error; we need the extra
 // parameter too, so the macro shoehorns it in there
-#define yyerror(msg) grampar_yyerror(msg, YYPARSE_PARAM)
+#define yyerror(parseParam, msg) grampar_yyerror(parseParam, msg)
 
 // rename the externally-visible parsing routine to make it
 // specific to this instance, so multiple bison-generated
@@ -59,7 +59,9 @@
 
 /* ================== bison declarations =================== */
 // don't use globals
-%pure_parser
+%pure-parser
+%parse-param {void* parseParam}
+%lex-param {void* parseParam}
 
 
 /* ===================== tokens ============================ */
```
```
--- src/elkhound/Makefile.in.orig	2015-11-29 17:57:45.000000000 -0600
+++ src/elkhound/Makefile.in	2015-11-29 18:03:09.000000000 -0600
@@ -208,8 +208,7 @@
 	mv -f grampar.tab.h tmp
 	sed -e 's/typedef union {/typedef union YYSTYPE {/' <tmp >grampar.tab.h
 	rm tmp
-	head -n 70 grampar.tab.h > grampar.codes.h
-#	grep '# *define' grampar.tab.h >grampar.codes.h
+	grep -A 2 -B 5 TOK_ grampar.tab.h >grampar.codes.h
 
 
 # new C++ grammar with treebuilding actions
```
Success!

I want to package this for MacPorts, but I don't see a make install file. I looked through the tutorial and besides the binaries it seems I'll need the runtime libraries and headers for elkhound, ast & smbase if the user wants to build a parser using Elkhound.

**Comment by FredrikLindgren** [comment]
Awesome! Thanks a lot.
Elkhound builds over here too, after changing the initialisation value of yyval in the Makefile. Will push and merge into master.

I don't know about packaging Elkhound. WeiDU only needs the elkhound binary itself.
